spring.security.oauth2.client.registration.google.redirect-uri=http://168.138.147.219.nip.io/login/oauth2/code/google

app.oauth2.redirect-uri=http://168.138.147.219.nip.io

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
